### ISSUE TITLE
注册时，密码可以为空

### ISSUE THREAD

**Issue by DillionApple** [DillionApple/fdugeek-vue#1]

**Comment by j7168908jx** [comment]
后台已经增加密码验证，需要前台相应常驻设置密码的提示：在注册和修改密码时后台要求密码6-20位，有大写字母，小写字母，数字，特殊符号（!@#$%^&*）4种中至少2种。

**Comment by j7168908jx** [comment]
建议顺便提示一下尽可能不要用和学邮一样的密码？

**Comment by DillionApple** [comment]
#8 #9 修复了该bug
